extract = 'total_dyn_inst: (\d+)'
benchmarks = '../examples/test/lvn/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brilirs -p {args}",
]

[runs.tdce]
pipeline = [
    "bril2json",
    "python3 ../examples/tdce.py tdce+",
    "brilirs -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "python3 ../examples/lvn.py -p -c -f",
    "python3 ../examples/tdce.py tdce+",
    "brilirs -p {args}",
]

[runs.dce]
pipeline = [
    "bril2json",
    "python3 ../assignment/dce.py",
    "brilirs -p {args}",
]
